name: GitHub Actions CI

on:
  push:
    branches: 
      - main
      - build-with-ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat /etc/*-release
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker build docker/ -t benchmarks
      - run: docker tag benchmarks $DOCKER_USERNAME/benchmarks
      - run: docker push $DOCKER_USERNAME/benchmarks