---
image: ubuntu:latest
before_script:
  - cat /proc/cpuinfo
  - cat /etc/os-release
  - sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  - apt-cache policy docker-ce
  - sudo apt install docker-ce -y
  - sudo /etc/init.d/docker start

stages:
  - build-job
  - run-job

build-job:
  stage: build
  script:
  - cat /etc/*-release
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build docker/ -t benchmarks
  - docker tag benchmarks $DOCKER_USERNAME/benchmarks
  - docker push $DOCKER_USERNAME/benchmarks


run-job:
  stage: run
  script:
  - pwd
  - ls
  - docker run -it --rm -v $(pwd):/src $DOCKER_USERNAME/benchmarks base64 bench
