services:
  - docker

jobs:
  include:
    - stage: build
      script: 
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build docker/ -t benchmarks .
      - docker push $DOCKER_USERNAME/benchmarks
      
    - stage: run
      script: docker run -it --rm -v $DOCKER_USERNAME/benchmarks brainfuck bench


# && docker run -it --rm -v $(pwd):/src benchmarks brainfuck bench
# jobs:
#   include:
#     - stage: build docker image
#       script:
#       - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#       - docker build -t travis-ci-build-stages-demo .
#       - docker images
#       - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
#       - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo
#     - stage: test
#       script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
#     - script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt


# language: c

# compiler:
#   - gcc

# jobs:
#   include:
#     - stage: test
#       addons:
#         apt:
#           update: true 
#           - cmake
#           - libcunit1-dev
#       script:
#         - cd ./examples/c
#         - cmake test
#         - make
#         - ./unit-test
#     - stage: build
#       addons:
#         apt:
#           update: true
#           packages:
#           - cmake
#           - build-essential
#       script:
#         - cd ./examples/c
#         - cmake src
#         - make