services:
  - docker

jobs:
  include:
    - stage: build
      script: docker build docker/ -t benchmarks && docker run -it --rm -v $(pwd):/src benchmarks brainfuck bench

    # - stage: run
    #   script: docker run -it --rm -v $(pwd):/src benchmarks brainfuck bench




# language: c

# compiler:
#   - gcc

# jobs:
#   include:
#     - stage: test
#       addons:
#         apt:
#           update: true 
#           - cmake
#           - libcunit1-dev
#       script:
#         - cd ./examples/c
#         - cmake test
#         - make
#         - ./unit-test
#     - stage: build
#       addons:
#         apt:
#           update: true
#           packages:
#           - cmake
#           - build-essential
#       script:
#         - cd ./examples/c
#         - cmake src
#         - make