version: 2.1
jobs:
  build-and-run:
    machine: true
    steps:
      - checkout
      - run: cat /etc/*-release
      - run: docker build docker/ -t benchmarks
      # - run: docker run -it --rm -v $(pwd):/src benchmarks brainfuck bench

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-run
